### DISCUSSION TITLE
How To: Talos on CAPMOX

### DISCUSSION THREAD

**Discussion by tamcore** [ionos-cloud/cluster-api-provider-proxmox#405] [Ideas]
Not exactly an idea, but there's no other option to choose from :)

Since Talos is a recurring topic, i figured, although it's not officially supported here, sharing some manifests with the community might be a good idea.

To note: I had issues getting any sort of extensions working, when using the `.machine.install` section of the talos machine configuration (which is deprecated anyways: https://www.talos.dev/v1.9/talos-guides/configuration/system-extensions/). So the only reliable option to get the qemu-guest-agent up and running was to have it baked into the image right from the beginning (which is preferable anyways IMHO)

As the first step, we have to download the nocloud image with qemu-guest-agent baked in and register it as a VM template in Proxmox.

The url for the image is the `Disk Image` referenced on https://factory.talos.dev/?arch=amd64&cmdline-set=true&extensions=-&extensions=siderolabs%2Fqemu-guest-agent&platform=nocloud&target=cloud&version=1.9.3

```bash
# Update the variables to your liking
VMID=10001
VMNAME=talos-nocloud-qemu-v1.9.3
VMTAGS="capi,talos,v1.9.3,qemu"
STORAGE=tank

# Don't change anything bellow this line
wget https://factory.talos.dev/image/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515/v1.9.3/nocloud-amd64.raw.xz

xz -d nocloud-amd64.raw.xz

qm create $VMID --name $VMNAME --tags "$VMTAGS"
qm importdisk $VMID nocloud-amd64.raw "$STORAGE"
qm set $VMID \
    --scsihw virtio-scsi-single  \
    --scsi0 $STORAGE:vm-$VMID-disk-0,discard=on,iothread=1,ssd=1  \
    --boot order=scsi0  \
    --cpu host  \
    --rng0 source=/dev/urandom  \
    --template 1  \
    --agent 1  \
    --onboot 1
```

After the VM is registered, we can start creating the cluster. In the manifests bellow, pay extra care to parameters like `allowedNodes`,  `controlPlaneEndpoint`, `dnsServers`, `ipv4Config` as well as `vip` in the `TalosControlPlane`, since you have to adjust those to match your setup.

```yaml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: talos
  namespace: cluster-api
spec:
  allowedNodes:
  - pve
  controlPlaneEndpoint:
    host: 192.168.69.80
    port: 6443
  dnsServers:
  - 8.8.8.8
  - 8.8.4.4
  ipv4Config:
    addresses:
    - 192.168.69.81-192.168.69.89
    gateway: 192.168.69.1
    prefix: 24
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: talos
  namespace: cluster-api
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: talos-control-plane
    namespace: cluster-api
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxCluster
    name: talos
    namespace: cluster-api
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: talos-control-plane
  namespace: cluster-api
spec:
  version: v1.32.1
  replicas: 3
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxMachineTemplate
    name: talos-control-plane
    namespace: cluster-api
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      strategicPatches:
        - |
          machine:
            install:
              disk: /dev/sda
              extraKernelArgs:
                - net.ifnames=0
            network:
              interfaces:
                - interface: eth0
                  dhcp: false
                  vip:
                    ip: 192.168.69.80
            kubelet:
              extraArgs:
                cloud-provider: external
            features:
              kubernetesTalosAPIAccess:
                enabled: true
                allowedRoles:
                  - os:reader
                allowedKubernetesNamespaces:
                  - kube-system
          cluster:
            externalCloudProvider:
              enabled: true
              manifests:
                - https://raw.githubusercontent.com/siderolabs/talos-cloud-controller-manager/main/docs/deploy/cloud-controller-manager.yml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: talos-control-plane
  namespace: cluster-api
spec:
  template:
    spec:
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 20
      format: qcow2
      full: true
      memoryMiB: 4096
      network:
        default:
          bridge: vmbr0
          model: virtio
      numCores: 1
      numSockets: 1
      sourceNode: pve
      templateID: 10001
      checks:
        skipCloudInitStatus: true
      metadataSettings:
        providerIDInjection: true
```

After deploying the above manifests, it takes about 4-5 minutes to spin up 3 healthy Talos control-plane nodes **with** Talos CCM working (so `spec.providerID` is properly set on every node)

Let's add some worker nodes
```yaml
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: talos-worker
  namespace: cluster-api
spec:
  clusterName: talos
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: talos-worker
      clusterName: talos
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: talos-worker
      version: v1.32.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: talos-worker
  namespace: cluster-api
spec:
  template:
    spec:
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 20
      format: qcow2
      full: true
      memoryMiB: 2048
      network:
        default:
          bridge: vmbr0
          model: virtio
      numCores: 1
      numSockets: 1
      sourceNode: pve
      templateID: 10001
      checks:
        skipCloudInitStatus: true
      metadataSettings:
        providerIDInjection: true
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: talos-worker
  namespace: cluster-api
spec:
  template:
    spec:
      generateType: worker
      strategicPatches:
        - |
          machine:
            install:
              disk: /dev/sda
              extraKernelArgs:
                - net.ifnames=0
            network:
              interfaces:
                - interface: eth0
                  dhcp: false
            kubelet:
              extraArgs:
                cloud-provider: external
```
