### ISSUE TITLE
Suport DHCP

### ISSUE THREAD

**Issue by mcbenjemaa** [ionos-cloud/cluster-api-provider-proxmox#29]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Our current setup is based on IPAM and static IP Allocation.
Since the QEMY-quest-agent is pre-installed, we can support dhcp in the network-config.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

PLEASE NOTE: since we rely on the kube-vip for control planes, the `CONTROL_PLANE_ENDPOINT` shall remain static and must be set when creating a new cluster.

**Environment:**

- Cluster-api-provider-proxmox version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by wikkyk** [comment]
This could be a good first candidate feature to port from https://github.com/k8s-proxmox/cluster-api-provider-proxmox.

**Comment by mcbenjemaa** [comment]
## Proposal 

Since introducing a new field can be a breaking change, we probably need to introduce a new API version.

There are three proposals as follows. 

 #### (1) v1alpha2 with DHCP option

In this case, v1alpha2 will be the default and the storage version 
Adding:
- `spec.ipv4Config.dhcp`
- `spec.ipv6Config.dhcp`

The ipam pool config will now be wrapped into `static`

The conversation webhook will convert v1alpha1 resources.

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ProxmoxCluster
metadata:
  name: "test-cluster"
spec:
  controlPlaneEndpoint:
    host: 10.10.10.3
    port: 6443
  ipv4Config:
    dhcp: true
  dnsServers: [10.1.1.1]
---
## OR

apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ProxmoxCluster
metadata:
  name: "test-cluster"
spec:
  controlPlaneEndpoint:
    host: 10.10.10.3
    port: 6443
  ipv4Config:
    static:
      addresses: ["10.10.10.5-10.10.10.60"]
      prefix: 24
      gateway: 10.10.10.1
  dnsServers: [10.1.1.1]
```

Apart from the changes in the ProxmoxCluster, 
a new field can also be introduced to the machines.

```yaml
kind: ProxmoxMachineTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
metadata:
  name: "test-control-plane"
spec:
  template:
    spec:
      sourceNode: "pve"
      templateID: 100
      format: "qcow2"
      full: true
      network:
        default:
          bridge: vmbr1
          model: virtio
          dhcp4: true  # This will force the machine to use DHCP instead of the cluster static config
          dhcp6: true  # This will cause the machine to use DHCP instead of the cluster static config
        additionalDevices:
        - name: net1
          bridge: vmbr2
          model: virtio
          dhcp4: true. # Either DHCP or ipam pool config must be defined 
          dhcp6: true. # Either DHCP or ipam pool config must be defined 
```

 #### (2) v1alpha1 with DHCP option

In this case the API is backward compatible and will not need to introduce v1alpha2.


```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: "test-cluster"
spec:
  controlPlaneEndpoint:
    host: 10.10.10.3
    port: 6443
  dhcp4: true # replaces ipv4config
  dhcp6: true  # replaces ipv6config
  dnsServers: [10.1.1.1]
```

 #### (3) machine v1alpha1 with DHCP option
in this case DHCP option is only available in the machine, while the cluster will set IP pool config as optional.
this is also a backward compatible 

```yaml
kind: ProxmoxMachineTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
metadata:
  name: "test-control-plane"
spec:
  template:
    spec:
      sourceNode: "pve"
      templateID: 100
      format: "qcow2"
      full: true
      network:
        default:
          bridge: vmbr1
          model: virtio
          dhcp4: true  # This will force the machine to use DHCP instead of the cluster static config
          dhcp6: true  # This will cause the machine to use DHCP instead of the cluster static config
        additionalDevices:
        - name: net1
          bridge: vmbr2
          model: virtio
          dhcp4: true. # Either DHCP or ipam pool config must be defined 
          dhcp6 true. # Either DHCP or ipam pool config must be defined 
```


For any further implementation, please suggest.

This require your attention @avorima
