### ISSUE TITLE
Machine gets stuck in provisioning state

### ISSUE THREAD

**Issue by khushalmer03** [ionos-cloud/cluster-api-provider-proxmox#291]
**What steps did you take and what happened:**
- I'm trying to provision a kubernetes cluster in proxmox VM using talos [bootstrap](https://github.com/siderolabs/cluster-api-bootstrap-provider-talos) and [controlplane](https://github.com/siderolabs/cluster-api-control-plane-provider-talos) provider
- I have deployed management cluster using capi-operator-system [helmchart](https://artifacthub.io/packages/helm/cluster-api-operator/cluster-api-operator) as I want to utilize GitOps using fluxCD. Below is my management cluster configurations: 
```
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-operator
  namespace: capi-operator-system
spec:
  releaseName: capi-operator
  interval: 15m
  timeout: 90s
  chart:
    spec:
      chart: "cluster-api-operator"
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: capi-operator
  values:
    core: "cluster-api:v1.7.5"
    infrastructure: "proxmox:v0.5.1"
    controlPlane: "talos:v0.5.6;kubeadm:v1.4.2"
    bootstrap: "talos:v0.6.5;kubeadm:v1.4.2"
    addon: "helm"
    manager:
      featureGates:
        core:
          ClusterTopology: true
          MachinePool: true
        proxmox:
          ClusterTopology: true
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: IPAMProvider
metadata:
  name: proxmox-ipam
  namespace: proxmox-infrastructure-system
spec:
  version: v0.1.0-alpha.3
  fetchConfig:
    url: https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases/download/v0.1.0-alpha.3/ipam-components.yaml

```

- I'm trying to deploy single controlPlane cluster using proxmox vm template with talos initialized in it. Below is my cluster manifest that I'm using to provision talos cluster in proxmox vm

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: talos-test
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.0.6.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: talos-test
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxCluster
    name: pride
  controlPlaneEndpoint:
    host: "10.0.1.164"
    port: 6443
  
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: pride
spec:
  controlPlaneEndpoint:
    host: "10.0.1.164"
    port: 6443
  ipv4Config:
    addresses: [10.0.1.174-10.0.1.175]
    prefix: 20
    gateway: 10.0.1.1
  dnsServers: [10.0.1.1]
  allowedNodes: [px1]
  credentialsRef:
    name: "pride-proxmox-credentials"

---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: talos-test
spec:
  version: v1.30.1
  replicas: 1
  infrastructureTemplate:
    kind: ProxmoxMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    name: talos-cp
  controlPlaneConfig:
    init:
      generateType: init
    controlplane:
      generateType: controlplane
      talosVersion: v1.7.4
        
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: "talos-cp"
spec:
  template:
    spec:
      sourceNode: "px1"
      templateID: 110
      format: "qcow2"
      full: true
      numSockets: 1
      numCores: 2
      memoryMiB: 2048
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 8
      network:
        default:
          bridge: vmbr0
          model: virtio
```

Now the machine is created successfully in proxmox with IP assigned to it as well but machine phase in the management cluster is stuck in provisioning state as a result no further action of bootstrapping by talos takes place as it keeps waiting for infrastructure to be ready. Upon cheking the logs of capmox-controller-manager, this is what I found: 
```
E0923 08:06:57.505071       1 controller.go:329] "Reconciler error" err="failed to reconcile VM: error waiting for agent: the operation has timed out" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="talos-cp2-n9h6b" name="talos-cp2-n9h6b" reconcileID="f55e43c1-ba7d-43f5-bbee-8c1fd90b3202"
```
Note that I have already enables qemu-agent in the VM template as well. 

Status of machine in management cluster: 

![image](https://github.com/user-attachments/assets/c1a81206-b838-4115-8dad-abbdf2c1589f)

**What did you expect to happen:**
Machine is provisioned successfully and control plane is initialized.

**Environment:**

- Cluster-api-provider-proxmox version:v0.5.1 
- Kubernetes version: (use `kubectl version`):v1.30.1
- OS (e.g. from `/etc/os-release`): talos:v1.7.4

**Comment by mcbenjemaa** [comment]
Please share the cluster manifest, you're using and let us debug

**Comment by rouke-broersma** [comment]
I have the same issue I think. Relevant capmox logs:

``` 
E1122 21:34:46.708828       1 proxmoxmachine_controller.go:209] "error reconciling VM" err="unable to get cloud-init status: no pid returned from agent exec command" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="embla-cluster/embla-proxmox-control-plane-machine-template-8tt4r" namespace="embla-cluster" name="embla-proxmox-control-plane-machine-template-8tt4r" reconcileID="b447c5f3-11b6-41bc-a800-b7a75182246e" machine="embla-cluster/embla-talos-control-plane-qfhts" cluster="embla-cluster/embla-cluster"
E1122 21:34:46.709446       1 controller.go:329] "Reconciler error" err="failed to reconcile VM: unable to get cloud-init status: no pid returned from agent exec command" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="embla-cluster/embla-proxmox-control-plane-machine-template-8tt4r" namespace="embla-cluster" name="embla-proxmox-control-plane-machine-template-8tt4r" reconcileID="b447c5f3-11b6-41bc-a800-b7a75182246e"
```

Templates: https://github.com/broersma-forslund/homelab/tree/90723ca8735a855e537ac792ce102a8ca5260f8f/apps/infrastructure/embla-cluster/templates

**Comment by rouke-broersma** [comment]
Can confirm that the issue I mentioned has been solved in talos 1.9 alpha.3. The only remaining issue I see is that capmox is not updating the node IPs in the machine CR which cause talos to wait with bootstrapping. This can be solved with the skipQemuCheck in the proxmoxmachine CR but this has not yet been released, it's on main only.

**Comment by rouke-broersma** [comment]
I also don't use image builder, I'm pretty sure that's only for kubeadm. Did you use a nocloud type talos image? Did you also disable the other check? Only qemu is not enough.

**Comment by khushalmer03** [comment]
@rouke-broersma 
- I did used talos v1.9.0-alpha.3
- Disabled both cloud init check and qemu check as well 
- Logs of proxmox controller says Proxmox machine is ready and machines are ready as well 
But taloscontrolplane says no such route to host as it is trying to access cluster on the IP that IPAM provider should ideally assigns from the InClusterIPPool
- But the nodes is getting the IP from my DHCP and not from the IPAM

Full configuration:
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-cluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: capi-talos-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxCluster
    name: capi-proxmox-cluster

---

apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: capi-proxmox-cluster
spec:
  credentialsRef:
    name: pride-proxmox-credentials
  allowedNodes: [px1]
  controlPlaneEndpoint:
    host: 10.0.15.241
    port: 6443
  dnsServers: [10.0.1.1]
  ipv4Config:
    gateway: 10.0.1.1
    prefix: 20
    addresses:
    - 10.0.15.242-10.0.15.250
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: capi-proxmox-control-plane-machine-template
spec:
  template:
    spec:
      full: true
      sourceNode: "px1"
      templateID: 103
      format: qcow2
      numSockets: 1
      numCores: 2
      memoryMiB: 2048
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 8
      network:
        default:
          bridge: vmbr0
          model: virtio
          # vlan: 254
      checks:
        skipQemuGuestAgent: true
        skipCloudInitStatus: true
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: capi-talos-control-plane
spec:
  replicas: 2
  version: v1.30.3
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxMachineTemplate
    name: capi-proxmox-control-plane-machine-template
  controlPlaneConfig:
    controlplane:
      talosVersion: v1.9.0
      generateType: controlplane
      hostname:
        source: MachineName
      configPatches:
      - op: add
        path: /machine/network
        value:
          interfaces:
          - dhcp: true
            interface: eth0
            vip:
              ip: 10.0.15.240
      - op: add
        path: /machine/install
        value:
          extraKernelArgs:
          - net.ifnames=0
```
Machines:

![image](https://github.com/user-attachments/assets/dcbe4655-94b1-4578-b1a4-e453302efcb3)

Taloscontrolplanes status:

![image](https://github.com/user-attachments/assets/5512f9a4-1c23-42dd-88b5-e63fa3e0fc78)

Note that I've given controlplane IP as 10.0.15.241 but taloscontrolplane is trying to access it on 10.0.15.242 which is IP from the ipv4Configs

**Comment by rouke-broersma** [comment]
Proxmox provider does not yet support dhcp, you need to disable dhcp. Also talos is trying to configure the node so of course it's trying to reach the node ip and not the control plane ip. Your node needs to be able to arp its assigned ip and should then be routable from your cluster api provider.

**Comment by lieberlois** [comment]
I have the same issue. Adding  `skipQemuGuestAgent: false` helps to successfully provision everything, and talos-cloud-controller-manager assigns the providerID etc. to the nodes - however in Proxmox, the UI still shows Guest Agent Not Running. Here are the manifests: https://gist.github.com/lieberlois/9a47412006ad9e47a617c0dc49bef7a2

**Comment by lieberlois** [comment]
@pborn-ionos Thanks, i'll check your link! I have the extension added to talos though - but of course I understand that it's not your guys' job to maintain the interaction with Talos 😉  I'll check and get back to you, thanks for the quick answer!

**Comment by khushalmer03** [comment]
I got it working following this [guide](https://a-cup-of.coffee/blog/talos-capi-proxmox/#cluster-api)! Thanks for great help !
@lieberlois Let me know if it works out for you and I'll close this issue.

**Comment by lieberlois** [comment]
@pborn-ionos Could it be related to VLAN NICs? After the full setup (with the workload cluster being reachable) it looks like this:

<img width="1318" alt="Image" src="https://github.com/user-attachments/assets/58f5df2a-7cda-42c2-960e-ade74e054f74" />

However right after applying the manifests (so basically the first boot cycle) it works:

<img width="1127" alt="Image" src="https://github.com/user-attachments/assets/bee7e7a3-ccf2-49a5-8758-d727891fe051" />

<img width="1257" alt="Image" src="https://github.com/user-attachments/assets/dd8cc1a7-85d3-45b0-929d-49465f97dd94" />

---

It seems like the Reboot during the Talos installation causes this to fail, but I don't quite understand the reason 🤔  I could of course add another NIC that is *NOT* tagged with a VLAN but I don't see why that would be required. Here is my full manifest:

https://gist.github.com/lieberlois/1bea39e345e4c22bee131f0ef70f7e19

**Comment by khushalmer03** [comment]
@lieberlois Your manifests looks good. Just a quick check
- When building talos iso image from image Factory, use Hardware type Cloud -> No Cloud. This was the bottleneck for me and I was able to solve it with correct iso image 

![Image](https://github.com/user-attachments/assets/412f0ced-ee98-4fe2-94f2-8c185a296109)

**Comment by lieberlois** [comment]
@khushalmer03 Yeah i have that 👍  as mentioned, during the first boot, it works for a short period of time - its probably some minor networking setting or something I override in my config.

**Comment by lieberlois** [comment]
Update: when using the nocloud variant **without** QEMU extension installed with Talos 1.9.6 + the following config patch then it works:

```yaml
        - op: replace
          path: /machine/install
          value:
            disk: /dev/sda
            extensions:
              - image: ghcr.io/siderolabs/qemu-guest-agent:9.2.0
```

However `/machine/install/extensions` is apparently deprecated and should no longer be used
