### ISSUE TITLE
incorrect cloudinit template (network gateway) with ipv6only setup

### ISSUE THREAD

**Issue by lucasl0st** [ionos-cloud/cluster-api-provider-proxmox#39]
The ipv6 address and gateway only get set correctly when it would get to this default case:

https://github.com/ionos-cloud/cluster-api-provider-proxmox/blob/a1666e478f0b4f990da0a0ef59a7f6d63397b2cd/internal/service/vmservice/bootstrap.go#L197C4-L197C4

It never gets to that default case because `len(config.MacAddress) == 0:` is true

Which results in a cloudinit template that looks like this (0.0.0.0 gateway instead of ::/0):

```
instance-id: e7fc6bd1-dd59-4d01-aa49-c1e9dade2672
local-hostname: proxmox-quickstart-control-plane-wvlt7
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      match:
        macaddress: BC:24:11:B9:4A:C3
      dhcp4: 'no'
      addresses:
        - 2a03:4000:20:18b:aaaa::a/64
      routes:
        - to: 0.0.0.0/0
          via: 2a03:4000:20:18b:be24:11ff:fe20:b2ed
      nameservers:
        addresses:
          - 2a03:4000:20:18b:be24:11ff:fe20:b2ed
```

Full configuration I used here: https://gist.github.com/lucasl0st/4fe31d5f9b936520f177c42efeb157e7

The v4/v6 should probably be handled in this function instead: https://github.com/ionos-cloud/cluster-api-provider-proxmox/blob/a1666e478f0b4f990da0a0ef59a7f6d63397b2cd/internal/service/vmservice/bootstrap.go#L144
