### ISSUE TITLE
[Talos] control-plane VM never created

### ISSUE THREAD

**Issue by no-fy** [ionos-cloud/cluster-api-provider-proxmox#392]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
After applying my cluster manifest consisting of a control plane and a worker node, the control plane VM is not created in proxmox. There is no request in the proxmox access logs nor in the tasks logs. I tried to create the quick-start cluster with ubuntu and kubeadm and it worked.
I don't see any error in the capmox controller, just this message:
 proxmoxcluster_controller.go:189] "Reconciling ProxmoxCluster" controller="proxmoxcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxCluster" ProxmoxCluster="default/capi-testcluster" namespace="default" name="capi-testcluster" reconcileID="a18fa8df-7 │

**What did you expect to happen:**
The control plane VM being created or a log that I can investigate in the capmox controller

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Here is my cluster manifest:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: capi-testcluster
  namespace: default
spec:
  allowedNodes:
  - pve
  controlPlaneEndpoint:
    host: 10.10.10.199
    port: 6443
  dnsServers:
  - 8.8.8.8
  - 8.8.4.4
  ipv4Config:
    addresses:
    - 10.10.10.200-10.10.10.220
    gateway: 10.10.10.1
    prefix: 24
---

apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-testcluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: capi-testcluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxCluster
    name: capi-testcluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: capi-testcluster-controlplane-template
  namespace: default
spec:
  template:
    spec:
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 50
      format: qcow2
      full: true
      memoryMiB: 8096
      network:
        default:
          bridge: vmbr100
          model: virtio
      numCores: 4
      numSockets: 1
      sourceNode: pve
      templateID: 8000
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: capi-testcluster-controlplane
  namespace: default
spec:
  version: v1.32.0
  replicas: 1
  infrastructureTemplate:
    kind: ProxmoxMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    name: capi-testcluster-controlplane-template
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: 1.9.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: capi-testcluster-worker-template
  namespace: default
spec:
  template:
    spec:
      full: true
      sourceNode: pve
      templateID: 300
      format: qcow2
      numSockets: 1
      numCores: 4
      memoryMiB: 16384
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 32
      network:
        default:
          bridge: vmbr100
          model: virtio
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: capi-testcluster-talos-worker-config
spec:
  template:
    spec:
      talosVersion: 1.9.1
      generateType: worker
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: capi-testcluster-talos-worker
spec:
  clusterName: capi-testcluster
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: capi-testcluster
      cluster.x-k8s.io/control-plane: "false"
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: capi-testcluster
        cluster.x-k8s.io/control-plane: "false"
    spec:
      clusterName: capi-testcluster
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfig
          name: capi-testcluster-talos-worker-config
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: capi-testcluster-worker-template
```
**Environment:**

- Cluster-api-provider-proxmox version: v0.6.2
- Kubernetes version: (use `kubectl version`): v1.131.4+k3s1
- OS (e.g. from `/etc/os-release`): Ubuntu 24.04.1 LTS
