### ISSUE TITLE
ProviderID is not set on Kubernetes Node spec

### ISSUE THREAD

**Issue by iverberk** [ionos-cloud/cluster-api-provider-proxmox#400]
**What steps did you take and what happened:**
I'm not sure if this is the right place to report so please let me know if the bug/problem I'm experiencing is likely in the Talos components.

I'm trying to setup a new controlplane based on Proxmox and Talos. I'm using the following versions and configurations:
```
Installing provider="cluster-api" version="v1.9.4" targetNamespace="capi-system"
Installing provider="bootstrap-talos" version="v0.6.7" targetNamespace="cabpt-system"
Installing provider="control-plane-talos" version="v0.5.8" targetNamespace="cacppt-system"
Installing provider="infrastructure-proxmox" version="v0.6.2" targetNamespace="capmox-system"
Installing provider="ipam-in-cluster" version="v1.0.0" targetNamespace="capi-ipam-in-cluster-system"
```
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: management
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: mgmt-talos-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxCluster
    name: mgmt-proxmox-cluster
```
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: mgmt-proxmox-cluster
spec:
  controlPlaneEndpoint:
    host: 172.16.0.5
    port: 6443
  dnsServers:
    - 8.8.8.8
    - 8.8.4.4
  ipv4Config:
    gateway: 172.16.0.1
    prefix: 24
    addresses:
    - 172.16.0.10-172.16.0.200
```
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: mgmt-proxmox-cp-machine-template
spec:
  template:
    spec:
      full: true
      sourceNode: opsteady
      templateID: 100
      format: qcow2
      numSockets: 1
      numCores: 2
      memoryMiB: 2048
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 32
      network:
        default:
          bridge: vmbr1
          model: virtio
      checks:
        skipCloudInitStatus: true
      metadataSettings:
        providerIDInjection: true
```
```
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: mgmt-talos-control-plane
spec:
  replicas: 1
  version: "1.32.0"
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxMachineTemplate
    name: mgmt-proxmox-cp-machine-template
    namespace: default
  controlPlaneConfig:
    controlplane:
      talosVersion: v1.9.2
      generateType: controlplane
      hostname:
        source: MachineName
      strategicPatches:
        - |
          machine:
            install:
              extensions:
                - image: ghcr.io/siderolabs/qemu-guest-agent:9.2.0
              disk: /dev/sda

              extraKernelArgs:
                - net.ifnames=0

            network:
              interfaces:
                - interface: eth0
                  dhcp: false
                  vip:
                    ip: 172.16.0.5
```
After applying these configurations, the control plane is setup successfully but the Kubernetes node itself never gets a providerID set on its spec. This causes the machine resource to never report ready:
```
Message:               * NodeHealthy: Waiting for a Node with spec.providerID proxmox://147e3fb5-d8da-4093-8262-a55da029a52b to exist
Observed Generation:   3
Reason:                ReadyUnknown
Status:                Unknown
Type:                  Ready
```

In the capi controller manager I see this message:
```
 I0202 14:44:24.236523       1 machine_controller_noderef.go:89] "Infrastructure provider reporting spec.providerID, matching Kubernetes node is not yet available" controller="machine" controllerGroup="cluster.x-k │
│ 8s.io" controllerKind="Machine" Machine="default/mgmt-talos-control-plane-rnrqw" namespace="default" name="mgmt-talos-control-plane-rnrqw" reconcileID="05ac6f70-a4df-431c-83fc-636bd338501b" Cluster="default/manag │
│ ement" TalosControlPlane="default/mgmt-talos-control-plane" ProxmoxMachine="default/mgmt-proxmox-cp-machine-template-p4n5z" providerID="proxmox://147e3fb5-d8da-4093-8262-a55da029a52b"
```

**What did you expect to happen:**
I'd expect that the Node resource gets a providerID set on the spec, so that the cluster API controller knows that the VM/Node has successfully registered with the control plane.

**Anything else you would like to add:**
I'm not sure where to look next. Which component is responsible for setting the providerID?

**Environment:**
I'm bootstrapping from a Kind cluster (1.32). OS:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"
```

Let me know if anything else is needed. Happy to provide more information if needed.
