### ISSUE TITLE
Failed Cluster with missing credentialsRef never reconciles

### ISSUE THREAD

**Issue by 65278** [ionos-cloud/cluster-api-provider-proxmox#484]
q**What steps did you take and what happened:**
My Cluster object is in a failed state because the referenced ProxmoxCluster resource had no credentialsRef.
I added the credentialsRef. The cluster object never reconciles:

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
[...]
status:                                                                                        
  conditions:                                                                                  
  - lastTransitionTime: "2025-05-19T11:55:58Z"                                                 
    status: "True"                                                                             
    type: Ready                    
  - lastTransitionTime: "2025-03-04T14:05:24Z"
    status: "True"                                                                             
    type: ControlPlaneInitialized
  - lastTransitionTime: "2025-05-19T11:55:58Z"                                                 
    status: "True"                                                                             
    type: ControlPlaneReady
  - lastTransitionTime: "2025-03-03T12:24:09Z"                                                 
    status: "True"                                                                             
    type: InfrastructureReady           
  controlPlaneReady: true                                                                      
  failureMessage: 'Failure detected from referenced resource infrastructure.cluster.x-k8s.io/v1alpha1,
    Kind=ProxmoxCluster with name "infra-prod": No credentials found, ProxmoxCluster
    missing credentialsRef'
  failureReason: InvalidConfiguration                                                          
  infrastructureReady: true   
  observedGeneration: 1                    
  phase: Failed           
```
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
spec:                                                                                          
[...]
credentialsRef:                                                                              
    name: capmox-infra-prod-credentials
    namespace: capi-clusters
[...]
status:
  conditions:
  - lastTransitionTime: "2025-03-03T12:24:09Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-03-03T12:24:09Z"
    status: "True"
    type: ClusterReady
```

**What did you expect to happen:**
Cluster object reconciles back to ready phase.

**Anything else you would like to add:**
Thanks for all the fish.

**Environment:**

- Proxmox version: 0.7.0
- Cluster-api-provider-proxmox version: 1.9.6
- Kubernetes version: (use `kubectl version`): 1.31.4
- OS (e.g. from `/etc/os-release`): ganoo+ubunnnuuuuu
