### ISSUE TITLE
PROXMOX_TOKEN in CAPMOX is PROXMOX_SECRET in the Image-Builder which is error-prone

### ISSUE THREAD

**Issue by 3deep5me** [ionos-cloud/cluster-api-provider-proxmox#52]
I created an image with image-builder, the environment variable for the "secret-key" is `PROXMOX_TOKEN`. 
In CAPMOX the same environment variable contains the "token-user". 

During the clusterctl init the environment variable is preferred over the config-file, so i ended up to have an secret like this
```
apiVersion: v1
data:
  secret: M3OWRi
  token: M3OWRi
  url: aHqc29u
```
I would like to suggest to have the same naming as in the image-builder to save others the trouble shooting.
`PROXMOX_USERNAME` & `PROXMOX_TOKEN`

I should be able to create a PR for that - if desired.
